-- V1: Initial schema - users, invoices, line_items
-- On existing databases this is skipped (Flyway baselines at V1).
-- On fresh databases this creates everything.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    provider VARCHAR(255),
    provider_id VARCHAR(255),
    is_guest BOOLEAN,
    is_disabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    company_logo VARCHAR(255),
    address VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    zip_code VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    company_email VARCHAR(255) NOT NULL,
    invoice_number VARCHAR(255) NOT NULL UNIQUE,
    invoice_date DATE NOT NULL,
    due_date DATE NOT NULL,
    primary_color VARCHAR(255) NOT NULL,
    font_family VARCHAR(255) NOT NULL,
    client_name VARCHAR(255),
    client_company VARCHAR(255),
    client_address VARCHAR(255),
    client_city VARCHAR(255),
    client_zip VARCHAR(255),
    client_country VARCHAR(255),
    tax_rate DOUBLE PRECISION,
    discount DOUBLE PRECISION,
    notes VARCHAR(2000),
    client_email VARCHAR(255),
    email_subject VARCHAR(255),
    email_message VARCHAR(2000),
    total_amount NUMERIC(38, 2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    user_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE line_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    rate NUMERIC(38, 2) NOT NULL,
    amount NUMERIC(38, 2) NOT NULL,
    invoice_id BIGINT NOT NULL,
    CONSTRAINT fk_line_items_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id)
);
